### ISSUE TITLE
[Bug]: Critical Hit & Fumble Deck, green font hard to read when Kingmaker style activate.

### ISSUE THREAD

**Issue by Sasmira** [foundryvtt/foundryvtt-premium-content#398]
### What happened?

A bug happened!

Hello Hello, 
alors, on m'a dit que je pouvais écrire en francais !

Le probleme c'est simple, lorsque l'utilisateur active le style Kingmaker dans les journaux des Critical hit/ Fumble Deck, la police des dommages, des conditions, des jets de sauvegarde etc etc ... devient Verte sur un fond  transparent. Le probleme étant que le fond d'origine des journaux des Critical hit/ Fumble est vert foncé et Bleu foncé ce qui rend la lecture illisible.

je te met un screenshot histoire d'expliquer visuellement le probleme

<img src="https://puu.sh/JSJq9/0251c4c489.jpg">

Si besoin je suis sur le discord PF2e / Foundry 
 

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by Sasmira** [comment]
Bon alors il semblerait que cela soit 4 lignes à rajouter pour corriger le probleme. Apres a toi de choisir la couleur :D

```CSS
div.journal-sheet.window-app.pf2e-km .journal-page-content .fumble-deck blockquote a {
  color: darkorange;
}
div.journal-sheet.window-app.pf2e-km .journal-page-content .fumble-deck blockquote .fa-comment-alt:before, div.journal-sheet.window-app.pf2e-km .fa-message:before {
  color: darkorange;
}
div.journal-sheet.window-app.pf2e-km .journal-page-content .critical-deck blockquote a {
  color: darkorange;
}
div.journal-sheet.window-app.pf2e-km .journal-page-content .critical-deck blockquote .fa-comment-alt:before, div.journal-sheet.window-app.pf2e-km .fa-message:before {
  color: darkorange;
}
```
