### ISSUE TITLE
DMG module spoils embedded NPC statblocks in 4.3

### ISSUE THREAD

**Issue by ctbritt** [foundryvtt/foundryvtt-premium-content#966]
Have run Find the Culprit twice and this is occurring when DMG module is enabled. 

![Image](https://github.com/user-attachments/assets/9961c61c-c875-4f13-a649-1874c9267098)

This shows what it looks like with only the DMG module enabled. 

Foundry 12.331
DnD5e 4.3
DMG: 1.1.0

**Comment by ctbritt** [comment]
It also happens with PHB and Tasha's sheets

**Comment by Gregory-Jagermeister** [comment]
A Quick Work around i have found for this so far is using the Custom Css Module with this Css snippet

```css
.sheet.journal-entry.dnd5e2-journal.dmg .statblock.npc .statblock-header .abilities thead th,
.sheet.journal-entry.dnd5e2-journal.dmg .statblock.npc .statblock-header .abilities tbody td{
	padding: 0px;
}
```
You may have to add the PHB and Tasha's Identifier aswell.
